### ISSUE TITLE
Octoprint default behavior drops serial connection to klipper

### ISSUE THREAD

**Issue by goeland86** [intelligent-agent/Refactor#248] opened 2021-11-06 19:19 UTC
OctoPrint's default behavior drops the serial connection.
Klipper keeps running and can receive commands even if errors occured.

We should modify the default OctoPrint behavior in the config to cancel ongoing prints but stay connected instead.

**Comment by eliasbakken** [comment] 2021-11-06 19:20
Duplicate of #245

**Closed by eliasbakken** 2021-11-06 19:20 UTC
Labels: duplicate, enhancement
